name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}

jobs:
  Lagom:

    strategy:
      fail-fast: false
      matrix:
        os_name: ['Linux']
        os: [depot-ubuntu-24.04, depot-ubuntu-22.04, depot-ubuntu-24.04-8, depot-ubuntu-22.04-8, depot-ubuntu-24.04-16, depot-ubuntu-22.04-16, depot-ubuntu-24.04-32, depot-ubuntu-22.04-32]

        fuzzer: ['NO_FUZZ']
        toolchain: ['GNU']
        clang_plugins: [false]


    uses: ./.github/workflows/lagom-template.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      os_name: ${{ matrix.os_name }}
      os: ${{ matrix.os }}
      fuzzer: ${{ matrix.fuzzer }}
      clang_plugins: ${{ matrix.clang_plugins }}
